### ISSUE TITLE
Orders Not Working On Website

### ISSUE THREAD

**Issue by Chattaeus** [AccelerateNetworks/NumberSearch#216]
**Describe the bug**
Was trying to place an order for phones on the website and for a customer and when checking out the screen went white. No loading bar or spinning progress wheel or anything like that.

**To Reproduce**
1. Go to our website.
2. Click on Hardware
3. Add phones to cart.
4. Check out
5. See error.

**Expected behavior**
I expected the order to be placed and generate an invoice.

**Screenshots**
![image](https://user-images.githubusercontent.com/73979793/128954382-d4ad99f7-4917-4b12-8628-4e4675b1b312.jpeg)
![image2](https://user-images.githubusercontent.com/73979793/128954976-4744f2a0-6a26-4314-a748-46d779ab73e8.jpg)

**Desktop (please complete the following information):**
 - OS: The crappy one from Microsoft, Windows 10
 - Browser The best, Firefox
 - Version 90.0.2 (admittedly one behind)

**Smartphone (please complete the following information):**
N/A

**Additional context**
Order for 2x Grandstream DP720 associated with email teizi.mersai@lamseafood.com

**Comment by uncheckederror** [comment]
I can see that the order was created in the Ops app. But it looks like something happened during the creation of the invoices, because the order doesn't have any references to the invoices like it should. 🤔

**Comment by uncheckederror** [comment]
From the logs on the webserver:

2021-08-10 17:52:27.427 -07:00 [INF] Executing action method NumberSearch.Mvc.Controllers.CartController.SubmitAsync (NumberSearch.Mvc) - Validation state: "Valid"
2021-08-10 17:52:27.428 -07:00 [INF] {"PhoneNumbers":[],"Products":[{"ProductId":"8317d56d-5937-41d5-9064-530406af295d","Name":"DP720","Price":85,"Description":"Need a solution that can serve your workplace with$2021-08-10 17:52:27.431 -07:00 [INF] [Checkout] Parsing address data from
2021-08-10 17:52:27.432 -07:00 [INF] [Checkout] Address: 1221 S King St City: Seattle State: WA Zip: 98144
2021-08-10 17:52:27.916 -07:00 [INF] [Checkout] Seattle, WA - 1726 @ 10.3.
2021-08-10 17:52:27.980 -07:00 [INF] [Checkout] Found billing client LAM'S SEAFOOD MARKET, 784.
2021-08-10 17:52:28.056 -07:00 [INF] Executed action NumberSearch.Mvc.Controllers.CartController.SubmitAsync (NumberSearch.Mvc) in 674.5215ms
2021-08-10 17:52:28.057 -07:00 [INF] Executed endpoint 'NumberSearch.Mvc.Controllers.CartController.SubmitAsync (NumberSearch.Mvc)'
2021-08-10 17:52:28.060 -07:00 [ERR] HTTP POST /Cart/Submit responded 500 in 679.7378 ms
Flurl.Http.FlurlHttpException: Call failed with status code 404 (Not Found): POST https://billing.acceleratenetworks.com/api/v1/invoices
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at NumberSearch.DataAccess.InvoiceNinja.InvoiceDatum.PostAsync(String token) in /home/vsts/work/1/s/NumberSearch.DataAccess/InvoiceNinja/Invoice.cs:line 132
   at NumberSearch.Mvc.Controllers.CartController.SubmitAsync(Order order) in /home/vsts/work/1/s/NumberSearch.Mvc/Controllers/CartController.cs:line 829
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean i$   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isComp$   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at NumberSearch.Mvc.Startup.<>c.<<Configure>b__5_1>d.MoveNext() in /home/vsts/work/1/s/NumberSearch.Mvc/Startup.cs:line 113
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at NetEscapades.AspNetCore.SecurityHeaders.SecurityHeadersMiddleware.Invoke(HttpContext context) in C:\projects\netescapades-aspnetcore-securityheaders\src\NetEscapades.AspNetCore.SecurityHeaders\SecurityHead$   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2021-08-10 17:52:28.180 -07:00 [ERR] An unhandled exception has occurred while executing the request.
Flurl.Http.FlurlHttpException: Call failed with status code 404 (Not Found): POST https://billing.acceleratenetworks.com/api/v1/invoices
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at NumberSearch.DataAccess.InvoiceNinja.InvoiceDatum.PostAsync(String token) in /home/vsts/work/1/s/NumberSearch.DataAccess/InvoiceNinja/Invoice.cs:line 132
   at NumberSearch.Mvc.Controllers.CartController.SubmitAsync(Order order) in /home/vsts/work/1/s/NumberSearch.Mvc/Controllers/CartController.cs:line 829
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean i$   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isComp$   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at NumberSearch.Mvc.Startup.<>c.<<Configure>b__5_1>d.MoveNext() in /home/vsts/work/1/s/NumberSearch.Mvc/Startup.cs:line 113
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at NetEscapades.AspNetCore.SecurityHeaders.SecurityHeadersMiddleware.Invoke(HttpContext context) in C:\projects\netescapades-aspnetcore-securityheaders\src\NetEscapades.AspNetCore.SecurityHeaders\SecurityHead$   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2021-08-10 17:52:28.198 -07:00 [INF] Executing endpoint '405 HTTP Method Not Supported'
2021-08-10 17:52:28.200 -07:00 [INF] Executed endpoint '405 HTTP Method Not Supported'
2021-08-10 17:52:28.201 -07:00 [INF] HTTP POST /Cart/Submit responded 405 in 3.0422 ms

**Comment by danry25** [comment]
From billing.acceleratenetworks.com's /var/log/nginx/access.log.1:
```
167.172.125.63 - - [10/Aug/2021:17:52:27 -0700] "GET /api/v1/tax_rates HTTP/1.1" 200 5052 "-" "-"
167.172.125.63 - - [10/Aug/2021:17:52:27 -0700] "GET /api/v1/clients?email=teizi.mersai@lamseafood.com HTTP/1.1" 200 2466 "-" "-"
167.172.125.63 - - [10/Aug/2021:17:52:28 -0700] "POST /api/v1/invoices HTTP/1.1" 404 46 "-" "-"
```
I found nothing in /var/log/nginx/error.log or /var/log/php7.3-fpm.log, any chance we could get or recreate the data that was posted to this endpoint?

**Comment by uncheckederror** [comment]
@danry25 yeah, if you just resubmit the order it should happen again?

**Comment by Chattaeus** [comment]
![image](https://user-images.githubusercontent.com/73979793/129102115-fcd0fd22-01d2-41f1-bec5-933d5dca658d.png)

It worked this time.

**Comment by uncheckederror** [comment]
@Chattaeus Nice, so I think we have proof then that was an intermittent error. I will add some retry logic to the creation of the invoices in the checkout process and then close this issue.
