### ISSUE TITLE
Porting in Numbers - SQL Error

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#239]
**Describe the bug**
When checking out phone numbers you would like to port on AccelerateNetworks.com, the order is generated with no products (eg: the phone numbers you would like to port) associated with the order and https://acceleratenetworks.com/Cart/Submit returns an HTTP 405 error.

**To Reproduce**
1. Go to [https://acceleratenetworks.com/Lookup/BulkPort?dialedNumber=2068588757](https://acceleratenetworks.com/Lookup/BulkPort?dialedNumber=2068588757)
2. Click on the Shopping Cart
3. Checkout the order

**Expected behavior**
The order should be generated properly with all items in the cart associated to the order

**Additional context**
Here is the error from the logs on the server:
```
2021-10-06 10:42:12.280 -07:00 [INF] Executed action NumberSearch.Mvc.Controllers.CartController.SubmitAsync (NumberSearch.Mvc) in 19.4375ms
2021-10-06 10:42:12.280 -07:00 [INF] Executed endpoint 'NumberSearch.Mvc.Controllers.CartController.SubmitAsync (NumberSearch.Mvc)'
2021-10-06 10:42:12.281 -07:00 [ERR] HTTP POST /Cart/Submit responded 500 in 20.5120 ms
Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "ProductOrders_pkey"
   at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in /_/Dapper/SqlMapper.Async.cs:line 646
   at NumberSearch.DataAccess.ProductOrder.PostAsync(String connectionString) in /home/vsts/work/1/s/NumberSearch.DataAccess/Models/ProductOrder.cs:line 69
   at NumberSearch.Mvc.Controllers.CartController.SubmitAsync(Order order) in /home/vsts/work/1/s/NumberSearch.Mvc/Controllers/CartController.cs:line 359
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean $
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCom$
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at NumberSearch.Mvc.Startup.<>c.<<Configure>b__5_1>d.MoveNext() in /home/vsts/work/1/s/NumberSearch.Mvc/Startup.cs:line 125
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at NetEscapades.AspNetCore.SecurityHeaders.SecurityHeadersMiddleware.Invoke(HttpContext context) in C:\projects\netescapades-aspnetcore-securityheaders\src\NetEscapades.AspNetCore.SecurityHeaders\SecurityHea$
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
  Exception data:
    Severity: ERROR
    SqlState: 23505
    MessageText: duplicate key value violates unique constraint "ProductOrders_pkey"
    Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
    SchemaName: public
    TableName: ProductOrders
    ConstraintName: ProductOrders_pkey
    File: nbtinsert.c
    Line: 534
    Routine: _bt_check_unique
2021-10-06 10:42:12.293 -07:00 [ERR] An unhandled exception has occurred while executing the request.
```

**Comment by uncheckederror** [comment]
@danry25 please verify that this is fixed by submitting your original bulk porting request.

**Comment by danry25** [comment]
@uncheckederror I was able to submit this successfully, thanks for fixing this!
