### ISSUE TITLE
NumberSearch Ingest Crashed

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#248]
**Describe the bug**
The ingest application fully crashed after 16 minutes of API query failures to Teli. Teli ticket 21789 has been opened to escalate this issue with them. 

Systemd Logs:
```
● numbersearchingest.service - NumberSearchIngest
   Loaded: loaded (/etc/systemd/system/numbersearchingest.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Wed 2021-12-15 07:36:41 PST; 9h ago
  Process: 14200 ExecStart=/usr/bin/dotnet /var/www/NumberSearch.Ingest/NumberSearch.Ingest.dll (code=killed, signal=ABRT)
 Main PID: 14200 (code=killed, signal=ABRT)

Dec 15 07:36:41 numberSearch dotnet[14200]:    at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
Dec 15 07:36:41 numberSearch dotnet[14200]:    at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
Dec 15 07:36:41 numberSearch dotnet[14200]:    at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
Dec 15 07:36:41 numberSearch dotnet[14200]:    at NumberSearch.DataAccess.TeliMesssage.LnpGet.GetAsync(String requestId, Guid token) in /home/vsts/work/1/s/NumberSearch.DataAccess/TeliMessage/LnpGet.cs:line 83
Dec 15 07:36:41 numberSearch dotnet[14200]:    at NumberSearch.Ingest.PortRequests.UpdateStatusesTeliMessageAsync(IConfiguration configuration) in /home/vsts/work/1/s/NumberSearch.Ingest/PortRequests.cs:line 254
Dec 15 07:36:41 numberSearch dotnet[14200]:    at NumberSearch.Ingest.Program.Main() in /home/vsts/work/1/s/NumberSearch.Ingest/Program.cs:line 518
Dec 15 07:36:41 numberSearch dotnet[14200]:    at NumberSearch.Ingest.Program.Main() in /home/vsts/work/1/s/NumberSearch.Ingest/Program.cs:line 843
Dec 15 07:36:41 numberSearch dotnet[14200]:    at NumberSearch.Ingest.Program.<Main>()
Dec 15 07:36:41 numberSearch systemd[1]: numbersearchingest.service: Main process exited, code=killed, status=6/ABRT
Dec 15 07:36:41 numberSearch systemd[1]: numbersearchingest.service: Failed with result 'signal'.
```

Journalctl logs:
```
Dec 15 07:21:56 numberSearch dotnet[14200]: [07:21:56 INF] [TeliMessage] Found 0 Phone Numbers for the 206 Area Code.
Dec 15 07:23:26 numberSearch dotnet[14200]: [07:23:26 ERR] NPA code 360 failed @ 12/15/2021 7:23:26 AM: Call failed. The SSL connection could not be established, see inner exception: GET https://apiv1.teleapi.ne
Dec 15 07:23:26 numberSearch dotnet[14200]: [07:23:26 INF] [TeliMessage] Found 0 Phone Numbers for the 360 Area Code.
Dec 15 07:25:06 numberSearch dotnet[14200]: [07:25:06 ERR] NPA code 425 failed @ 12/15/2021 7:25:06 AM: Call timed out: GET https://apiv1.teleapi.net/dids/list?token=redactedToken&npa=425
Dec 15 07:25:06 numberSearch dotnet[14200]: [07:25:06 INF] [TeliMessage] Found 0 Phone Numbers for the 425 Area Code.
Dec 15 07:26:46 numberSearch dotnet[14200]: [07:26:46 ERR] NPA code 503 failed @ 12/15/2021 7:26:46 AM: Call timed out: GET https://apiv1.teleapi.net/dids/list?token=redactedToken&npa=503
Dec 15 07:26:46 numberSearch dotnet[14200]: [07:26:46 INF] [TeliMessage] Found 0 Phone Numbers for the 503 Area Code.
Dec 15 07:28:26 numberSearch dotnet[14200]: [07:28:26 ERR] NPA code 509 failed @ 12/15/2021 7:28:26 AM: Call timed out: GET https://apiv1.teleapi.net/dids/list?token=redactedToken&npa=509
Dec 15 07:28:26 numberSearch dotnet[14200]: [07:28:26 INF] [TeliMessage] Found 0 Phone Numbers for the 509 Area Code.
Dec 15 07:30:06 numberSearch dotnet[14200]: [07:30:06 ERR] NPA code 541 failed @ 12/15/2021 7:30:06 AM: Call timed out: GET https://apiv1.teleapi.net/dids/list?token=redactedToken&npa=541
Dec 15 07:30:06 numberSearch dotnet[14200]: [07:30:06 INF] [TeliMessage] Found 0 Phone Numbers for the 541 Area Code.
Dec 15 07:31:46 numberSearch dotnet[14200]: [07:31:46 ERR] NPA code 564 failed @ 12/15/2021 7:31:46 AM: Call timed out: GET https://apiv1.teleapi.net/dids/list?token=redactedToken&npa=564
Dec 15 07:31:46 numberSearch dotnet[14200]: [07:31:46 INF] [TeliMessage] Found 0 Phone Numbers for the 564 Area Code.
Dec 15 07:33:26 numberSearch dotnet[14200]: [07:33:26 ERR] [TeliMessage] Call timed out: GET https://apiv1.teleapi.net/dids/list?token=redactedToken&type=tollfree System.Threading.Tasks.Ta
Dec 15 07:33:26 numberSearch dotnet[14200]:    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken canc
Dec 15 07:33:26 numberSearch dotnet[14200]:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean dispos
Dec 15 07:33:26 numberSearch dotnet[14200]:    at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
Dec 15 07:33:26 numberSearch dotnet[14200]: [07:33:26 INF] [TeliMessage] Found 0 Tollfree Phone Numbers.
Dec 15 07:33:26 numberSearch dotnet[14200]: [07:33:26 INF] [TeliMessage] Found 0 Phone Numbers
Dec 15 07:33:26 numberSearch dotnet[14200]: [07:33:26 INF] Ingesting the Ratecenters and Regions on 0 phone numbers.
Dec 15 07:33:26 numberSearch dotnet[14200]: [07:33:26 INF] Ingesting the Ratecenters and Regions on 0 phone numbers.
Dec 15 07:33:26 numberSearch dotnet[14200]: [07:33:26 INF] Updated 0 Phone Numbers
Dec 15 07:33:27 numberSearch dotnet[14200]: [07:33:27 INF] [TeliMessage] Completed the priority ingest process 12/15/2021 7:33:27 AM.
Dec 15 07:33:27 numberSearch dotnet[14200]: [07:33:27 INF] [TeliMessage] [PortRequests] Ingesting Port Request statuses.
Dec 15 07:36:38 numberSearch dotnet[14200]: [07:36:38 FTL] [Heartbeat] This is a complete application failure. We've broken out of the infinte loop.
Dec 15 07:36:41 numberSearch dotnet[14200]: Unhandled exception. Flurl.Http.FlurlHttpException: Call failed. The SSL connection could not be established, see inner exception: GET https://apiv1.teleapi.net/lnp/ge
Dec 15 07:36:41 numberSearch dotnet[14200]:  ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
Dec 15 07:36:41 numberSearch dotnet[14200]:  ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
Dec 15 07:36:41 numberSearch dotnet[14200]:    at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
Dec 15 07:36:41 numberSearch dotnet[14200]:    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
Dec 15 07:36:41 numberSearch dotnet[14200]:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, Ca
Dec 15 07:36:41 numberSearch dotnet[14200]:    --- End of inner exception stack trace ---
Dec 15 07:36:41 numberSearch dotnet[14200]:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, Ca
Dec 15 07:36:41 numberSearch dotnet[14200]:    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Dec 15 07:36:41 numberSearch dotnet[14200]:    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Dec 15 07:36:41 numberSearch dotnet[14200]:    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
Dec 15 07:36:41 numberSearch dotnet[14200]:    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
Dec 15 07:36:41 numberSearch dotnet[14200]:    at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Dec 15 07:36:41 numberSearch dotnet[14200]:    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken canc
Dec 15 07:36:41 numberSearch dotnet[14200]:    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Dec 15 07:36:41 numberSearch dotnet[14200]:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean dispos
Dec 15 07:36:41 numberSearch dotnet[14200]:    at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
Dec 15 07:36:41 numberSearch dotnet[14200]:    --- End of inner exception stack trace ---
Dec 15 07:36:41 numberSearch dotnet[14200]:    at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
Dec 15 07:36:41 numberSearch dotnet[14200]:    at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
Dec 15 07:36:41 numberSearch dotnet[14200]:    at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
Dec 15 07:36:41 numberSearch dotnet[14200]:    at NumberSearch.DataAccess.TeliMesssage.LnpGet.GetAsync(String requestId, Guid token) in /home/vsts/work/1/s/NumberSearch.DataAccess/TeliMessage/LnpGet.cs:line 83
Dec 15 07:36:41 numberSearch dotnet[14200]:    at NumberSearch.Ingest.PortRequests.UpdateStatusesTeliMessageAsync(IConfiguration configuration) in /home/vsts/work/1/s/NumberSearch.Ingest/PortRequests.cs:line 254
Dec 15 07:36:41 numberSearch dotnet[14200]:    at NumberSearch.Ingest.Program.Main() in /home/vsts/work/1/s/NumberSearch.Ingest/Program.cs:line 518
Dec 15 07:36:41 numberSearch dotnet[14200]:    at NumberSearch.Ingest.Program.Main() in /home/vsts/work/1/s/NumberSearch.Ingest/Program.cs:line 843
Dec 15 07:36:41 numberSearch dotnet[14200]:    at NumberSearch.Ingest.Program.<Main>()
Dec 15 07:36:41 numberSearch systemd[1]: numbersearchingest.service: Main process exited, code=killed, status=6/ABRT
Dec 15 07:36:41 numberSearch systemd[1]: numbersearchingest.service: Failed with result 'signal'.
```

Application Logs:
```
2021-12-15 07:20:52.292 -08:00 [INF] [TeliMessage] Ingesting priority data from TeleMessage
2021-12-15 07:20:52.293 -08:00 [INF] [TeliMessage] Found 7 NPAs
2021-12-15 07:21:56.727 -08:00 [ERR] NPA code 206 failed @ 12/15/2021 7:21:56 AM: Call failed. The SSL connection could not be established, see inner exception: GET https://apiv1.teleapi.net/dids/list?token=0a7$
2021-12-15 07:21:56.729 -08:00 [INF] [TeliMessage] Found 0 Phone Numbers for the 206 Area Code.
2021-12-15 07:23:26.388 -08:00 [ERR] NPA code 360 failed @ 12/15/2021 7:23:26 AM: Call failed. The SSL connection could not be established, see inner exception: GET https://apiv1.teleapi.net/dids/list?token=0a7$
2021-12-15 07:23:26.389 -08:00 [INF] [TeliMessage] Found 0 Phone Numbers for the 360 Area Code.
2021-12-15 07:25:06.403 -08:00 [ERR] NPA code 425 failed @ 12/15/2021 7:25:06 AM: Call timed out: GET https://apiv1.teleapi.net/dids/list?token=redactedToken&npa=425
2021-12-15 07:25:06.404 -08:00 [INF] [TeliMessage] Found 0 Phone Numbers for the 425 Area Code.
2021-12-15 07:26:46.404 -08:00 [ERR] NPA code 503 failed @ 12/15/2021 7:26:46 AM: Call timed out: GET https://apiv1.teleapi.net/dids/list?token=redactedToken&npa=503
2021-12-15 07:26:46.405 -08:00 [INF] [TeliMessage] Found 0 Phone Numbers for the 503 Area Code.
2021-12-15 07:28:26.406 -08:00 [ERR] NPA code 509 failed @ 12/15/2021 7:28:26 AM: Call timed out: GET https://apiv1.teleapi.net/dids/list?token=redactedToken&npa=509
2021-12-15 07:28:26.407 -08:00 [INF] [TeliMessage] Found 0 Phone Numbers for the 509 Area Code.
2021-12-15 07:30:06.407 -08:00 [ERR] NPA code 541 failed @ 12/15/2021 7:30:06 AM: Call timed out: GET https://apiv1.teleapi.net/dids/list?token=redactedToken&npa=541
2021-12-15 07:30:06.408 -08:00 [INF] [TeliMessage] Found 0 Phone Numbers for the 541 Area Code.
2021-12-15 07:31:46.409 -08:00 [ERR] NPA code 564 failed @ 12/15/2021 7:31:46 AM: Call timed out: GET https://apiv1.teleapi.net/dids/list?token=redactedToken&npa=564
2021-12-15 07:31:46.409 -08:00 [INF] [TeliMessage] Found 0 Phone Numbers for the 564 Area Code.
2021-12-15 07:33:26.447 -08:00 [ERR] [TeliMessage] Call timed out: GET https://apiv1.teleapi.net/dids/list?token=redactedToken&type=tollfree System.Threading.Tasks.TaskCanceledException: $
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pend$
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingReques$
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
2021-12-15 07:33:26.449 -08:00 [INF] [TeliMessage] Found 0 Tollfree Phone Numbers.
2021-12-15 07:33:26.449 -08:00 [INF] [TeliMessage] Found 0 Phone Numbers
2021-12-15 07:33:26.449 -08:00 [INF] Ingesting the Ratecenters and Regions on 0 phone numbers.
2021-12-15 07:33:26.450 -08:00 [INF] Ingesting the Ratecenters and Regions on 0 phone numbers.
2021-12-15 07:33:26.452 -08:00 [INF] Updated 0 Phone Numbers
2021-12-15 07:33:27.349 -08:00 [INF] [TeliMessage] Completed the priority ingest process 12/15/2021 7:33:27 AM.
2021-12-15 07:33:27.350 -08:00 [INF] [TeliMessage] [PortRequests] Ingesting Port Request statuses.
2021-12-15 07:36:38.634 -08:00 [FTL] [Heartbeat] This is a complete application failure. We've broken out of the infinte loop.
```

**Expected behavior**
The failing vendor should be ignored, and the application should not fail to restart for hours on end (this is perhaps a systemd unit file issue).

**Additional context**
The Journalctl log has useful info on the crash at timestamp 07:36:41

**Comment by danry25** [comment]
Teli has advised that this issue should be fixed, and the ingest process has ran over the last 19 hours without issue:
```
● numbersearchingest.service - NumberSearchIngest
   Loaded: loaded (/etc/systemd/system/numbersearchingest.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-12-15 19:14:56 PST; 19h ago
```
@uncheckederror Are you interested in adding code to handle Flurl.Http.FlurlHttpException gracefully perchance?

**Comment by uncheckederror** [comment]
Heheheh, those failure logs are the graceful handling of that exception.

'''Dec 15 07:36:41 numberSearch dotnet[14200]: Unhandled exception. Flurl.Http.FlurlHttpException: Call failed. The SSL connection could not be established, see inner exception: GET https://apiv1.teleapi.net/lnp/get'''

Is the call that caused the Ingest app to crash. I'll have to add more error handling to the Port Request status update process.

**Comment by uncheckederror** [comment]
@danry25 I have deployed a new version of the Ingest app that adds additional error handling for the scenario where Teli's API fails to respond with a list of port request statuses.
