### ISSUE TITLE
SystemD reports that numbersearchingest.service has failed 

### ISSUE THREAD

**Issue by piajesse** [AccelerateNetworks/NumberSearch#267]
**Describe the bug**
Been getting emails saying this service has failed for a while, just went to check what the logs were but there aren't any.

**Screenshots**
<img width="866" alt="Screen Shot 2022-01-22 at 2 38 39 PM" src="https://user-images.githubusercontent.com/44306072/150657725-c5ec350d-64f7-4194-9503-996ef918a2f1.png">
<img width="578" alt="Screen Shot 2022-01-22 at 2 43 27 PM" src="https://user-images.githubusercontent.com/44306072/150657737-3c78938d-3c62-40e0-b400-a7a4fb0da93d.png">

**Additional context**
not sure if I should restart the process or leave it alone, I have alerted @danry25 about it, but it looks like nothing has happened so I'm reporting it here.

**Comment by danry25** [comment]
Here is the crash log from the application:
```
tail -28 20211216_NumberSearch.Ingest20220120.txt 
2022-01-20 10:39:13.803 -08:00 [INF] [BulkVS] Completed the port request update process.
2022-01-20 10:39:13.824 -08:00 [INF] [FirstPointCom] Ingesting priority data from FirstPointCom
2022-01-20 10:40:13.996 -08:00 [ERR] Area code 206 failed @ 1/20/2022 10:40:13 AM: The request channel timed out attempting to send after 00:01:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
2022-01-20 10:41:14.059 -08:00 [ERR] Area code 360 failed @ 1/20/2022 10:41:14 AM: The request channel timed out attempting to send after 00:01:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
2022-01-20 10:42:14.112 -08:00 [ERR] Area code 425 failed @ 1/20/2022 10:42:14 AM: The request channel timed out attempting to send after 00:01:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
2022-01-20 10:43:14.142 -08:00 [ERR] Area code 503 failed @ 1/20/2022 10:43:14 AM: The request channel timed out attempting to send after 00:01:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
2022-01-20 10:44:14.214 -08:00 [ERR] Area code 509 failed @ 1/20/2022 10:44:14 AM: The request channel timed out attempting to send after 00:01:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
2022-01-20 10:45:14.267 -08:00 [ERR] Area code 541 failed @ 1/20/2022 10:45:14 AM: The request channel timed out attempting to send after 00:01:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
2022-01-20 10:46:14.320 -08:00 [ERR] Area code 564 failed @ 1/20/2022 10:46:14 AM: The request channel timed out attempting to send after 00:01:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
2022-01-20 10:46:14.320 -08:00 [INF] Ingesting the Ratecenters and Regions on 0 phone numbers.
2022-01-20 10:46:14.320 -08:00 [INF] Ingesting the Ratecenters and Regions on 0 phone numbers.
2022-01-20 10:46:14.320 -08:00 [INF] Updated 0 Phone Numbers
2022-01-20 10:46:29.325 -08:00 [FTL] [Heartbeat] This is a complete application failure. We've broken out of the infinte loop.
2022-01-20 10:46:34.360 -08:00 [FTL] [Email] Failed to send email 00000000-0000-0000-0000-000000000000.
2022-01-20 10:46:34.361 -08:00 [FTL] Resource temporarily unavailable
2022-01-20 10:46:34.391 -08:00 [FTL]    at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, ValueStopwatch stopwatch)
   at System.Net.Dns.<>c.<GetHostEntryOrAddressesCoreAsync>b__33_0(Object s, ValueStopwatch stopwatch)
   at System.Net.Dns.<>c__DisplayClass39_0`1.<RunAsync>b__0(Task <p0>, Object <p1>)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Int32 timeout, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.MailService.ConnectSocket(String host, Int32 port, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at NumberSearch.DataAccess.Email.SendEmailAsync(String username, String password) in /home/vsts/work/1/s/NumberSearch.DataAccess/Models/Email.cs:line 173
```

**Comment by piajesse** [comment]
I am no longer getting emails, so it appears that its all working now
