### ISSUE TITLE
Call48 ingest failed

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#305]
The ingest app crash last night. Here are the log lines immediately proceeding the crash event.

```
2022-11-26 08:00:11.015 -08:00 [INF] [Call48] Found 18585 Phone Numbers
2022-11-26 08:00:11.016 -08:00 [INF] Ingesting the Ratecenters and Regions on 18585 phone numbers.
2022-11-26 08:01:08.627 -08:00 [INF] Ingesting the Ratecenters and Regions on 18585 phone numbers.
2022-11-26 08:01:11.423 -08:00 [INF] Found 169 new Phone Numbers to Insert.
2022-11-26 08:01:11.424 -08:00 [INF] Found 18416 existing Phone Numbers to Update.
2022-11-26 08:01:11.566 -08:00 [FTL] Name or service not known
2022-11-26 08:01:11.578 -08:00 [FTL] Object reference not set to an instance of an object.
2022-11-26 08:01:11.604 -08:00 [FTL]    at NumberSearch.Ingest.Services.<>c__DisplayClass2_0.<<SubmitPhoneNumbersAsync>b__2>d.MoveNext() in /home/vsts/work/1/s/NumberSearch.Ingest/Servic$--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at NumberSearch.Ingest.Services.SubmitPhoneNumbersAsync(PhoneNumber[] numbers, String connectionString) in /home/vsts/work/1/s/NumberSearch.Ingest/Services.cs:line 192
   at NumberSearch.Ingest.Provider.Call48Async(String username, String password, AreaCodesByState[] states, String connectionString) in /home/vsts/work/1/s/NumberSearch.Ingest/Provider.c$   at NumberSearch.Ingest.Program.Main() in /home/vsts/work/1/s/NumberSearch.Ingest/Program.cs:line 851
2022-11-26 08:01:11.605 -08:00 [FTL] No inner exception message found.
2022-11-26 08:01:11.605 -08:00 [FTL] No inner exception stack trace found.
2022-11-26 08:01:11.606 -08:00 [FTL] [Heartbeat] This is a complete application failure. We've broken out of the infinte loop.
```

**Comment by uncheckederror** [comment]
Closing as a duplicate.
