### ISSUE TITLE
Call48 ingest failed

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#306]
The ingest app crashed last night. Here are the log lines immediately proceeding the crash event.

```
2022-11-26 08:00:11.015 -08:00 [INF] [Call48] Found 18585 Phone Numbers
2022-11-26 08:00:11.016 -08:00 [INF] Ingesting the Ratecenters and Regions on 18585 phone numbers.
2022-11-26 08:01:08.627 -08:00 [INF] Ingesting the Ratecenters and Regions on 18585 phone numbers.
2022-11-26 08:01:11.423 -08:00 [INF] Found 169 new Phone Numbers to Insert.
2022-11-26 08:01:11.424 -08:00 [INF] Found 18416 existing Phone Numbers to Update.
2022-11-26 08:01:11.566 -08:00 [FTL] Name or service not known
2022-11-26 08:01:11.578 -08:00 [FTL] Object reference not set to an instance of an object.
2022-11-26 08:01:11.604 -08:00 [FTL]    at NumberSearch.Ingest.Services.<>c__DisplayClass2_0.<<SubmitPhoneNumbersAsync>b__2>d.MoveNext() in /home/vsts/work/1/s/NumberSearch.Ingest/Servic$--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at NumberSearch.Ingest.Services.SubmitPhoneNumbersAsync(PhoneNumber[] numbers, String connectionString) in /home/vsts/work/1/s/NumberSearch.Ingest/Services.cs:line 192
   at NumberSearch.Ingest.Provider.Call48Async(String username, String password, AreaCodesByState[] states, String connectionString) in /home/vsts/work/1/s/NumberSearch.Ingest/Provider.c$   at NumberSearch.Ingest.Program.Main() in /home/vsts/work/1/s/NumberSearch.Ingest/Program.cs:line 851
2022-11-26 08:01:11.605 -08:00 [FTL] No inner exception message found.
2022-11-26 08:01:11.605 -08:00 [FTL] No inner exception stack trace found.
2022-11-26 08:01:11.606 -08:00 [FTL] [Heartbeat] This is a complete application failure. We've broken out of the infinte loop.
```

**Comment by uncheckederror** [comment]
Based on a quick google the message "Name or service not known" appears to be a issue where the connection to the database from the ingest app failed. I don't see a good way to solve this, so I think we'll wait and see if it happens again for now.

**Comment by uncheckederror** [comment]
It failed again last night here the log:

```
2022-11-26 22:59:03.872 -08:00 [INF] [Peerless] Found 18693 Phone Numbers for Rate Center YONCALLA
2022-11-26 22:59:03.872 -08:00 [INF] Ingesting the Ratecenters and Regions on 18693 phone numbers.
2022-11-26 22:59:28.851 -08:00 [INF] Ingesting the Ratecenters and Regions on 18693 phone numbers.
2022-11-26 22:59:43.958 -08:00 [FTL] The operation has timed out.
2022-11-26 22:59:44.050 -08:00 [FTL]    at Npgsql.TaskTimeoutAndCancellation.ExecuteAsync(Func`2 getTaskFunc, NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.TaskTimeoutAndCancellation.ExecuteAsync[TResult](Func`2 getTaskFunc, NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.RawOpen(SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
   at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|204_1(NpgsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean is$   at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.PoolingDataSource.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.PoolingDataSource.<Get>g__RentAsync|28_0(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|45_0(Boolean async, CancellationToken cancellationToken)
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 459
   at NumberSearch.DataAccess.PhoneNumber.GetAllNumbersAsync(String connectionString) in /home/vsts/work/1/s/NumberSearch.DataAccess/Models/PhoneNumber.cs:line 66
   at NumberSearch.DataAccess.PhoneNumber.GetAllNumbersAsync(String connectionString) in /home/vsts/work/1/s/NumberSearch.DataAccess/Models/PhoneNumber.cs:line 66
   at NumberSearch.Ingest.Services.SubmitPhoneNumbersAsync(PhoneNumber[] numbers, String connectionString) in /home/vsts/work/1/s/NumberSearch.Ingest/Services.cs:line 137
   at NumberSearch.Ingest.Provider.PeerlessAsync(String[] ratecenters, String peerlessAPIKey, String connectionString) in /home/vsts/work/1/s/NumberSearch.Ingest/Provider.cs:line 70
   at NumberSearch.Ingest.Program.Main() in /home/vsts/work/1/s/NumberSearch.Ingest/Program.cs:line 851
2022-11-26 22:59:44.053 -08:00 [FTL] No inner exception message found.
2022-11-26 22:59:44.053 -08:00 [FTL] No inner exception stack trace found.
2022-11-26 22:59:44.058 -08:00 [FTL] [Heartbeat] This is a complete application failure. We've broken out of the infinte loop.
```

**Comment by uncheckederror** [comment]
No crashes have occurred since last year for the Call48 provider so I am closing this issue out.
