### ISSUE TITLE
Potential issue with OAuth in the Ops application?

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#48]
It looks like the OAuth portion of the Ops application is causing crashes?

```
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
Jul 19 18:41:36 numberSearch dotnet[20854]: fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[3]
Jul 19 18:41:36 numberSearch dotnet[20854]:       An exception was thrown attempting to execute the error handler.
Jul 19 18:41:36 numberSearch dotnet[20854]: System.ArgumentException: The 'ClientId' option must be provided. (Parameter 'ClientId')
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.AspNetCore.Authentication.OAuth.OAuthOptions.Validate()
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.AspNetCore.Authentication.RemoteAuthenticationOptions.Validate(String scheme)
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.AspNetCore.Authentication.AuthenticationBuilder.<>c__DisplayClass4_0`2.<AddSchemeHelper>b__1(TOptions o)
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.Extensions.Options.ValidateOptions`1.Validate(String name, TOptions options)
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass11_0.<Get>b__0()
Jul 19 18:41:36 numberSearch dotnet[20854]:    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
Jul 19 18:41:36 numberSearch dotnet[20854]: --- End of stack trace from previous location where exception was thrown ---
Jul 19 18:41:36 numberSearch dotnet[20854]:    at System.Lazy`1.CreateValue()
Jul 19 18:41:36 numberSearch dotnet[20854]:    at System.Lazy`1.get_Value()
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
Jul 19 18:41:36 numberSearch dotnet[20854]: fail: Microsoft.AspNetCore.Server.Kestrel[13]
Jul 19 18:41:36 numberSearch dotnet[20854]:       Connection id "0HM1C9O4VSULS", Request id "0HM1C9O4VSULS:00000001": An unhandled exception was thrown by the application.
Jul 19 18:41:36 numberSearch dotnet[20854]: System.ArgumentException: The 'ClientId' option must be provided. (Parameter 'ClientId')
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.AspNetCore.Authentication.OAuth.OAuthOptions.Validate()
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.AspNetCore.Authentication.RemoteAuthenticationOptions.Validate(String scheme)
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.AspNetCore.Authentication.AuthenticationBuilder.<>c__DisplayClass4_0`2.<AddSchemeHelper>b__1(TOptions o)
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.Extensions.Options.ValidateOptions`1.Validate(String name, TOptions options)
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass11_0.<Get>b__0()
Jul 19 18:41:36 numberSearch dotnet[20854]:    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
Jul 19 18:41:36 numberSearch dotnet[20854]: --- End of stack trace from previous location where exception was thrown ---
Jul 19 18:41:36 numberSearch dotnet[20854]:    at System.Lazy`1.CreateValue()
Jul 19 18:41:36 numberSearch dotnet[20854]:    at System.Lazy`1.get_Value()
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
Jul 19 18:41:36 numberSearch dotnet[20854]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by uncheckederror** [comment]
This appears to be resolved please verify that it's fixed @danry25.
